spring.application.name=BazaarCore – Multi-Vendor Commerce Backend

spring.datasource.url=jdbc:mysql://localhost:3306/BazaarCore_db
spring.datasource.username=root
spring.datasource.password=Mandan@123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true

app.admin.name=System Admin
app.admin.email=jhanintyeight@gmail.com
app.admin.password=Admin@123
app.admin.phone=9999999999

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mandanjha07@Gmail.com
spring.mail.password=mmjqswrftjouudcl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

